### PR TITLE
set user agent

### LINKED ISSUE #8: set user agent

### PR DESCRIPTION
**Pull request by zeke**
This will give us a way to track how much API usage we're getting from this thing.

@mattt @jakedahn @erbridge I'd love your input on a sensible user agent string.

Resolves #8

### CODE REVIEW

**Comment by mattt** [comment]
For the JS client, we set a default user agent of `replicate-javascript/${packageJSON.version}`. We could annotate it to be something like `replicate-javascript/{v} create-replicate/{vv}`. Or maybe just `create-replicate/{create-version}`, since we don't have a nice way to get the client version (without creating a new client and inspecting its default user agent).

**Comment by mattt** [comment]
On second thought, we may not need to change anything in the generated output to gauge impact of this tool. We could instead:

- Look at weekly download statistics from npmjs.com
- Add opt-out telemetry in `index.js` to record when a project is created for a particular model

**Comment by zeke** [comment]
Thanks for weighing in, @mattt 

> Add opt-out telemetry in `index.js` to record when a project is created for a particular model

What would that look like?

**Comment by zeke** [comment]
I'm gonna go ahead and merge this as-is. We can watch the download numbers and  follow up with telemetry if wanted, but I don't think it hurts anything to have this in here too.

**Pull request merged**
