### PR TITLE
feat: Update .gitignore

### PR DESCRIPTION
**Pull request by superhighfives**
Dropped in a more fully featured `.gitignore` from https://github.com/github/gitignore/blob/main/Node.gitignore.

### CODE REVIEW

**Review by zeke — APPROVED** [review]
Nice!

I updated the PR title to add a semantic prefix, but unfortunately CI is failing due to some recent changes we made to tighten up GitHub token requirements in the @replicate org:

> Error: `replicate` forbids access via a personal access token (classic). Please use a GitHub App, OAuth App, or a personal access token with fine-grained permissions.

I'll work on getting that sorted.

**Comment by zeke** [comment]
Screenshot 2024-06-27 at 12 05 08

Whoop whoop!

Okay so I updated the token in the repo secrets with a new scoped PAT that only has fine-grained access to this one repo.

We're unblocked on CI. Lets see if it works for cutting a release, too. 🤞🏼

**Comment by zeke** [comment]
Release PR: https://github.com/replicate/create-replicate/pull/49

**Comment by zeke** [comment]
Boom.

Screenshot 2024-06-27 at 12 09 12

**Comment by superhighfives** [comment]
Awesome, thanks so much @zeke. 😊

**Pull request merged**
